### PR TITLE
Fix add_extra_stereo_audio causing exception when the audio stream has no language tag. Added option to generate stream if no language

### PR DESCRIPTION
**Pull request by WillBeasley**
I had an issue where some video files had no language tag for their audio streams and add_extra_stereo_pair was throwing an exception. I have fixed the issue where an exception is thrown (see the debug.log statement)

I have added a configuration option to generate if there is an audio stream that matches the other requirements but has no language tag also.

### CODE REVIEW

**Comment by yajrendrag** [comment]
Thanks.  Why did you remove this line: `if "tags" in probe_streams[i] and "title" in probe_streams[i]["tags"] and probe_streams[i]["tags"]["title"] == 'Commentary':`

**Comment by WillBeasley** [comment]
> Thanks. Why did you remove this line: `if "tags" in probe_streams[i] and "title" in probe_streams[i]["tags"] and probe_streams[i]["tags"]["title"] == 'Commentary':`

Ah, good spot I believe I have delete that by mistake, I have corrected that error now.

**Comment by yajrendrag** [comment]
@WillBeasley thanks for fixing the debug logger and good option added.  There's a comment in the description.md that mentions that the file needs to have valid language tags in order for the plugin to work, so you might correct that too - something like "enable the force_if_no_lang option to include audio streams without language tags"..

**Comment by WillBeasley** [comment]
> @WillBeasley thanks for fixing the debug logger and good option added.  There's a comment in the description.md that mentions that the file needs to have valid language tags in order for the plugin to work, so you might correct that too - something like "enable the force_if_no_lang option to include audio streams without language tags"..  

OK, I have updated this now

**Comment by yajrendrag** [comment]
@Josh5 - you can approve & merge..

**Comment by Josh5** [comment]
@yajrendrag Can you please setup a repo in your own GitHub org to receive this PR.

@WillBeasley Once that is done, could you please open a PR to @yajrendrag who is the maintainer of this Plugin.


Thanks :sweat_smile:

**Pull request closed without merging**
